version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8686:8686"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8686"
    environment:
      - DB_HOST=mongodb
      - DB_NAME=blogdb
      - DB_USER=admin
      - DB_PASS=password
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: blogdb
    ports:
      - 27017:27017
