version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8686:8686"
    volumes:
      - ./app:/app
    command: python manage.py runserver 0.0.0.0:8686
    environment:
      - DB_HOST=mongodb
      - DB_NAME=blogdb
      - DB_USER=admin
      - DB_PASS=password
    links:
      - mongodb
    depends_on:
      - migration

  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: blogdb
    ports:
      - 27017:27017

  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/app
    links:
      - mongodb
    depends_on:
      - make_migrations

  make_migrations:
    build: .
    image: app
    command: python manage.py makemigrations
    volumes:
      - .:/app
    links:
      - mongodb
    depends_on:
      - mongodb